Add link for pax-construct 1.5 binary.  To use Maven 3.x, you need to use at least 1.5 to avoid this error
NoSuchMethodError:
org.apache.maven.project.MavenProject.addPlugin(Lorg/apache/maven/model/Plugin;)V

when running "mvn clean install" on the test\test.bundle.